/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedAgendaRouteImport } from './routes/_authenticated/agenda'
import { Route as AuthenticatedClientesRouteImport } from './routes/_authenticated/clientes'
import { Route as AuthenticatedComissoesRouteImport } from './routes/_authenticated/comissoes'
import { Route as AuthenticatedConciliacaoRouteImport } from './routes/_authenticated/conciliacao'
import { Route as AuthenticatedConferenciaRouteImport } from './routes/_authenticated/conferencia'
import { Route as AuthenticatedConfiguracoesRouteImport } from './routes/_authenticated/configuracoes'
import { Route as AuthenticatedEstoqueRouteImport } from './routes/_authenticated/estoque'
import { Route as AuthenticatedFinanceiroRouteImport } from './routes/_authenticated/financeiro'
import { Route as AuthenticatedHistoricoRouteImport } from './routes/_authenticated/historico'
import { Route as AuthenticatedMesRouteImport } from './routes/_authenticated/mes'
import { Route as AuthenticatedPainelRouteImport } from './routes/_authenticated/painel'
import { Route as AuthenticatedRecibosRouteImport } from './routes/_authenticated.recibos'
import { Route as AuthenticatedSemanaRouteImport } from './routes/_authenticated/semana'
import { Route as AuthenticatedTrocaRouteImport } from './routes/_authenticated/troca'
import { Route as AuthenticatedVendasRouteImport } from './routes/_authenticated/vendas'
import { Route as ApiPublicPagbankWebhookRouteImport } from './routes/api/public/pagbank-webhook'
import { Route as ApiPublicReciboTokenRouteImport } from './routes/api/public/recibo.$token'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAgendaRoute = AuthenticatedAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedClientesRoute = AuthenticatedClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedComissoesRoute = AuthenticatedComissoesRouteImport.update({
  id: '/comissoes',
  path: '/comissoes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConciliacaoRoute =
  AuthenticatedConciliacaoRouteImport.update({
    id: '/conciliacao',
    path: '/conciliacao',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedConferenciaRoute =
  AuthenticatedConferenciaRouteImport.update({
    id: '/conferencia',
    path: '/conferencia',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedConfiguracoesRoute =
  AuthenticatedConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEstoqueRoute = AuthenticatedEstoqueRouteImport.update({
  id: '/estoque',
  path: '/estoque',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFinanceiroRoute = AuthenticatedFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHistoricoRoute = AuthenticatedHistoricoRouteImport.update({
  id: '/historico',
  path: '/historico',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMesRoute = AuthenticatedMesRouteImport.update({
  id: '/mes',
  path: '/mes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPainelRoute = AuthenticatedPainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRecibosRoute = AuthenticatedRecibosRouteImport.update({
  id: '/recibos',
  path: '/recibos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSemanaRoute = AuthenticatedSemanaRouteImport.update({
  id: '/semana',
  path: '/semana',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTrocaRoute = AuthenticatedTrocaRouteImport.update({
  id: '/troca',
  path: '/troca',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedVendasRoute = AuthenticatedVendasRouteImport.update({
  id: '/vendas',
  path: '/vendas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicPagbankWebhookRoute = ApiPublicPagbankWebhookRouteImport.update({
  id: '/api/public/pagbank-webhook',
  path: '/api/public/pagbank-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicReciboTokenRoute = ApiPublicReciboTokenRouteImport.update({
  id: '/api/public/recibo/$token',
  path: '/api/public/recibo/$token',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/agenda': typeof AuthenticatedAgendaRoute
  '/clientes': typeof AuthenticatedClientesRoute
  '/comissoes': typeof AuthenticatedComissoesRoute
  '/conciliacao': typeof AuthenticatedConciliacaoRoute
  '/conferencia': typeof AuthenticatedConferenciaRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/estoque': typeof AuthenticatedEstoqueRoute
  '/financeiro': typeof AuthenticatedFinanceiroRoute
  '/historico': typeof AuthenticatedHistoricoRoute
  '/mes': typeof AuthenticatedMesRoute
  '/painel': typeof AuthenticatedPainelRoute
  '/recibos': typeof AuthenticatedRecibosRoute
  '/semana': typeof AuthenticatedSemanaRoute
  '/troca': typeof AuthenticatedTrocaRoute
  '/vendas': typeof AuthenticatedVendasRoute
  '/api/public/pagbank-webhook': typeof ApiPublicPagbankWebhookRoute
  '/api/public/recibo/$token': typeof ApiPublicReciboTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/agenda': typeof AuthenticatedAgendaRoute
  '/clientes': typeof AuthenticatedClientesRoute
  '/comissoes': typeof AuthenticatedComissoesRoute
  '/conciliacao': typeof AuthenticatedConciliacaoRoute
  '/conferencia': typeof AuthenticatedConferenciaRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/estoque': typeof AuthenticatedEstoqueRoute
  '/financeiro': typeof AuthenticatedFinanceiroRoute
  '/historico': typeof AuthenticatedHistoricoRoute
  '/mes': typeof AuthenticatedMesRoute
  '/painel': typeof AuthenticatedPainelRoute
  '/recibos': typeof AuthenticatedRecibosRoute
  '/semana': typeof AuthenticatedSemanaRoute
  '/troca': typeof AuthenticatedTrocaRoute
  '/vendas': typeof AuthenticatedVendasRoute
  '/api/public/pagbank-webhook': typeof ApiPublicPagbankWebhookRoute
  '/api/public/recibo/$token': typeof ApiPublicReciboTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/agenda': typeof AuthenticatedAgendaRoute
  '/_authenticated/clientes': typeof AuthenticatedClientesRoute
  '/_authenticated/comissoes': typeof AuthenticatedComissoesRoute
  '/_authenticated/conciliacao': typeof AuthenticatedConciliacaoRoute
  '/_authenticated/conferencia': typeof AuthenticatedConferenciaRoute
  '/_authenticated/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/_authenticated/estoque': typeof AuthenticatedEstoqueRoute
  '/_authenticated/financeiro': typeof AuthenticatedFinanceiroRoute
  '/_authenticated/historico': typeof AuthenticatedHistoricoRoute
  '/_authenticated/mes': typeof AuthenticatedMesRoute
  '/_authenticated/painel': typeof AuthenticatedPainelRoute
  '/_authenticated/recibos': typeof AuthenticatedRecibosRoute
  '/_authenticated/semana': typeof AuthenticatedSemanaRoute
  '/_authenticated/troca': typeof AuthenticatedTrocaRoute
  '/_authenticated/vendas': typeof AuthenticatedVendasRoute
  '/api/public/pagbank-webhook': typeof ApiPublicPagbankWebhookRoute
  '/api/public/recibo/$token': typeof ApiPublicReciboTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/agenda'
    | '/clientes'
    | '/comissoes'
    | '/conciliacao'
    | '/conferencia'
    | '/configuracoes'
    | '/estoque'
    | '/financeiro'
    | '/historico'
    | '/mes'
    | '/painel'
    | '/recibos'
    | '/semana'
    | '/troca'
    | '/vendas'
    | '/api/public/pagbank-webhook'
    | '/api/public/recibo/$token'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/agenda'
    | '/clientes'
    | '/comissoes'
    | '/conciliacao'
    | '/conferencia'
    | '/configuracoes'
    | '/estoque'
    | '/financeiro'
    | '/historico'
    | '/mes'
    | '/painel'
    | '/recibos'
    | '/semana'
    | '/troca'
    | '/vendas'
    | '/api/public/pagbank-webhook'
    | '/api/public/recibo/$token'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/agenda'
    | '/_authenticated/clientes'
    | '/_authenticated/comissoes'
    | '/_authenticated/conciliacao'
    | '/_authenticated/conferencia'
    | '/_authenticated/configuracoes'
    | '/_authenticated/estoque'
    | '/_authenticated/financeiro'
    | '/_authenticated/historico'
    | '/_authenticated/mes'
    | '/_authenticated/painel'
    | '/_authenticated/recibos'
    | '/_authenticated/semana'
    | '/_authenticated/troca'
    | '/_authenticated/vendas'
    | '/api/public/pagbank-webhook'
    | '/api/public/recibo/$token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicPagbankWebhookRoute: typeof ApiPublicPagbankWebhookRoute
  ApiPublicReciboTokenRoute: typeof ApiPublicReciboTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/agenda': {
      id: '/_authenticated/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AuthenticatedAgendaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clientes': {
      id: '/_authenticated/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof AuthenticatedClientesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/comissoes': {
      id: '/_authenticated/comissoes'
      path: '/comissoes'
      fullPath: '/comissoes'
      preLoaderRoute: typeof AuthenticatedComissoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/conciliacao': {
      id: '/_authenticated/conciliacao'
      path: '/conciliacao'
      fullPath: '/conciliacao'
      preLoaderRoute: typeof AuthenticatedConciliacaoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/conferencia': {
      id: '/_authenticated/conferencia'
      path: '/conferencia'
      fullPath: '/conferencia'
      preLoaderRoute: typeof AuthenticatedConferenciaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/configuracoes': {
      id: '/_authenticated/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AuthenticatedConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/estoque': {
      id: '/_authenticated/estoque'
      path: '/estoque'
      fullPath: '/estoque'
      preLoaderRoute: typeof AuthenticatedEstoqueRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/financeiro': {
      id: '/_authenticated/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof AuthenticatedFinanceiroRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/historico': {
      id: '/_authenticated/historico'
      path: '/historico'
      fullPath: '/historico'
      preLoaderRoute: typeof AuthenticatedHistoricoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mes': {
      id: '/_authenticated/mes'
      path: '/mes'
      fullPath: '/mes'
      preLoaderRoute: typeof AuthenticatedMesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/painel': {
      id: '/_authenticated/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof AuthenticatedPainelRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/recibos': {
      id: '/_authenticated/recibos'
      path: '/recibos'
      fullPath: '/recibos'
      preLoaderRoute: typeof AuthenticatedRecibosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/semana': {
      id: '/_authenticated/semana'
      path: '/semana'
      fullPath: '/semana'
      preLoaderRoute: typeof AuthenticatedSemanaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/troca': {
      id: '/_authenticated/troca'
      path: '/troca'
      fullPath: '/troca'
      preLoaderRoute: typeof AuthenticatedTrocaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vendas': {
      id: '/_authenticated/vendas'
      path: '/vendas'
      fullPath: '/vendas'
      preLoaderRoute: typeof AuthenticatedVendasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/pagbank-webhook': {
      id: '/api/public/pagbank-webhook'
      path: '/api/public/pagbank-webhook'
      fullPath: '/api/public/pagbank-webhook'
      preLoaderRoute: typeof ApiPublicPagbankWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/recibo/$token': {
      id: '/api/public/recibo/$token'
      path: '/api/public/recibo/$token'
      fullPath: '/api/public/recibo/$token'
      preLoaderRoute: typeof ApiPublicReciboTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAgendaRoute: typeof AuthenticatedAgendaRoute
  AuthenticatedClientesRoute: typeof AuthenticatedClientesRoute
  AuthenticatedComissoesRoute: typeof AuthenticatedComissoesRoute
  AuthenticatedConciliacaoRoute: typeof AuthenticatedConciliacaoRoute
  AuthenticatedConferenciaRoute: typeof AuthenticatedConferenciaRoute
  AuthenticatedConfiguracoesRoute: typeof AuthenticatedConfiguracoesRoute
  AuthenticatedEstoqueRoute: typeof AuthenticatedEstoqueRoute
  AuthenticatedFinanceiroRoute: typeof AuthenticatedFinanceiroRoute
  AuthenticatedHistoricoRoute: typeof AuthenticatedHistoricoRoute
  AuthenticatedMesRoute: typeof AuthenticatedMesRoute
  AuthenticatedPainelRoute: typeof AuthenticatedPainelRoute
  AuthenticatedRecibosRoute: typeof AuthenticatedRecibosRoute
  AuthenticatedSemanaRoute: typeof AuthenticatedSemanaRoute
  AuthenticatedTrocaRoute: typeof AuthenticatedTrocaRoute
  AuthenticatedVendasRoute: typeof AuthenticatedVendasRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAgendaRoute: AuthenticatedAgendaRoute,
  AuthenticatedClientesRoute: AuthenticatedClientesRoute,
  AuthenticatedComissoesRoute: AuthenticatedComissoesRoute,
  AuthenticatedConciliacaoRoute: AuthenticatedConciliacaoRoute,
  AuthenticatedConferenciaRoute: AuthenticatedConferenciaRoute,
  AuthenticatedConfiguracoesRoute: AuthenticatedConfiguracoesRoute,
  AuthenticatedEstoqueRoute: AuthenticatedEstoqueRoute,
  AuthenticatedFinanceiroRoute: AuthenticatedFinanceiroRoute,
  AuthenticatedHistoricoRoute: AuthenticatedHistoricoRoute,
  AuthenticatedMesRoute: AuthenticatedMesRoute,
  AuthenticatedPainelRoute: AuthenticatedPainelRoute,
  AuthenticatedRecibosRoute: AuthenticatedRecibosRoute,
  AuthenticatedSemanaRoute: AuthenticatedSemanaRoute,
  AuthenticatedTrocaRoute: AuthenticatedTrocaRoute,
  AuthenticatedVendasRoute: AuthenticatedVendasRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicPagbankWebhookRoute: ApiPublicPagbankWebhookRoute,
  ApiPublicReciboTokenRoute: ApiPublicReciboTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
