
CREATE TABLE public.service_orders (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  os_number bigint GENERATED BY DEFAULT AS IDENTITY,
  customer_id uuid REFERENCES public.customers(id) ON DELETE SET NULL,
  customer_name text NOT NULL,
  kind text NOT NULL DEFAULT 'garantia',
  device_model text NOT NULL,
  imei text,
  serial_number text,
  color text,
  storage text,
  device_password text,
  reported_issue text,
  services text,
  parts text,
  total numeric NOT NULL DEFAULT 0,
  payment_method text,
  installments integer NOT NULL DEFAULT 1,
  status text NOT NULL DEFAULT 'aberta',
  warranty_days integer NOT NULL DEFAULT 90,
  notes text,
  responsible_id uuid,
  public_token text NOT NULL DEFAULT encode(gen_random_bytes(24), 'hex'),
  opened_at timestamptz NOT NULL DEFAULT now(),
  finished_at timestamptz,
  created_by uuid,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX service_orders_token_idx ON public.service_orders (public_token);
CREATE INDEX service_orders_customer_idx ON public.service_orders (customer_id);

GRANT SELECT, INSERT, UPDATE, DELETE ON public.service_orders TO authenticated;
GRANT ALL ON public.service_orders TO service_role;

ALTER TABLE public.service_orders ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Colaboradores veem as ordens de servico"
  ON public.service_orders FOR SELECT TO authenticated USING (true);
CREATE POLICY "Colaboradores criam ordens de servico"
  ON public.service_orders FOR INSERT TO authenticated WITH CHECK (auth.uid() IS NOT NULL);
CREATE POLICY "Colaboradores atualizam ordens de servico"
  ON public.service_orders FOR UPDATE TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Gerente exclui ordens de servico"
  ON public.service_orders FOR DELETE TO authenticated USING (public.is_gerente());

CREATE TRIGGER service_orders_updated_at BEFORE UPDATE ON public.service_orders
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();
